# https://theme-next.js.org/docs/

# Allow to cache content generation.
cache:
  enable: true

# Remove unnecessary files after hexo generate.
minify: true

scheme: Mist

avatar:
  url: /images/logo.jpg
  rounded: true

site_state: true

social_icons:
  enable: true
  icons_only: true
social:
  GitHub: https://github.com/xiaoheiit6 || fab fa-github
  E-Mail: mailto:xiaoheiit@foxmail.com || fa fa-envelope
  Telegram: https://t.me/xiaohei318 || fab fa-telegram


toc:
  enable: true
  number: true
  wrap: true
  expand_all: true

footer:
  since: 2023
  # Icon between year and copyright info.
  icon:
    # If you want to animate the icon, set it to true.
    animated: false
  

post_meta:
  item_text: true
  created_at: true
  updated_at:
    enable: true
    another_day: true

tag_icon: true

# Donate (Sponsor) settings
# Front-matter variable (nonsupport animation).
reward_settings:
  # If true, a donate button will be displayed in every article by default.
  enable: false
  animation: false
  #comment: Buy me a coffee
reward:
  #wechatpay:
  #alipay:
  #bitcoin:

related_posts:
  enable: true
  display_in_home: true
  params:
    maxCount: 5

# Preconnect CDN for fonts and plugins.
# For more information: https://www.w3.org/TR/resource-hints/#preconnect
preconnect: true

codeblock:
  # Code Highlight theme
  # All available themes: https://theme-next.js.org/highlight/
  theme:
    light: a11y-light
    dark: a11y-dark
  prism:
    light: prism
    dark: prism-dark

back2top:
  enable: true
  # Back to top in sidebar.
  sidebar: true
  # Scroll percent label in b2t button.
  scrollpercent: true

reading_progress:
  enable: true
  # Available values: left | right
  start_at: left
  # Available values: top | bottom
  position: top
  reversed: false
  color: "#37c6c0"
  height: 2px

bookmark:
  enable: false
  # Customize the color of the bookmark.
  color: "#222"
  # If auto, save the reading progress when closing the page or clicking the bookmark-icon.
  # If manual, only save it by clicking the bookmark-icon.
  save: auto

# Follow me on GitHub banner in right-top corner.
github_banner:
  enable: true
  permalink: https://github.com/xiaoheiit6
  title: Follow me on GitHub

creative_commons:
  # Available values: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | cc-zero
  license: by-nc-sa
  # Available values: big | small
  size: small
  sidebar: true
  post: true
  language: deed.zh

menu:
  home: / || fa fa-home
  #about: /about/ || fa fa-user
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  #schedule: /schedule/ || fa fa-calendar
  #sitemap: /sitemap.xml || fa fa-sitemap
  #commonweal: /404/ || fa fa-heartbeat

links:
  葛涛宁的博客: https://getaoning.com/


# Math Formulas Render Support
math:
  # Default (false) will load mathjax / katex script on demand.
  # That is it only render those page which has `mathjax: true` in front-matter.
  # If you set it to true, it will load mathjax / katex script EVERY PAGE.
  every_page: true

  mathjax:
    enable: true
    # Available values: none | ams | all
    tags: none

  katex:
    enable: false
    # See: https://github.com/KaTeX/KaTeX/tree/master/contrib/copy-tex
    copy_tex: false

# Microsoft Clarity Analytics
# See: https://clarity.microsoft.com/
#clarity_analytics: 

# Easily enable fast Ajax navigation on your website.
# For more information: https://github.com/next-theme/pjax
pjax: true

# Local search
local_search:
  enable: true

# Use Animate.css to animate everything.
# For more information: https://animate.style
motion:
  enable: false
  async: false

# TagCloud settings for tags page.
tagcloud:
  min: 12 # Minimum font size in px
  max: 30 # Maximum font size in px
  amount: 200 # Total amount of tags
  orderby: name # Order of tags
  order: 1 # Sort order